python_tests(name="tests")

python_source(
    name="proto_nx_script",
    source="proto_nx_script.py",
    resolve=parametrize("python-default", "nx28")
)

python_source(
    name="nx_lib",
    source="nx_lib.py",
    resolve=parametrize("python-default", "nx28")
)


python_source(
    name="nx_script",
    source="nx_script.py",
    resolve=parametrize("python-default", "nx28")
)
